name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: instalar dependências e rodar o build
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: |
          yarn
          yarn tsc

      - name: copiar arquivo via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }} #ubuntu
          port: ${{ secrets.PORT }} #22
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/app"

      - name: executando comandos ssh remotos
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app
            sudo docker-compose down
            sudo docker image prune
            sudo docker volume prune
            sudo docker network prune
            sudo docker-compose up -d
            sudo docker logs node1
            sudo docker logs node2
            sudo docker logs nginx-proxy
